### PR TITLE
Instrument run_in_executor to propagate current trace

### PR DESCRIPTION
**Pull request by GabrielCappelli**
_Before contributing, please read our [contributing guidelines](https://github.com/newrelic/newrelic-python-agent/blob/main/CONTRIBUTING.rst) and [code of conduct](https://github.com/newrelic/.github/blob/master/CODE_OF_CONDUCT.md)._

# Overview
Instruments `run_in_executor` in to propagate the current trace to the thread that will execute the requested function.

Instrumented loops:

asyncio.BaseEventLoop.run_in_executor
uvloop.Loop.run_in_executor

# Related Github Issue
https://github.com/newrelic/newrelic-python-agent/issues/657

# Testing
The agent includes a suite of tests which should be used to
verify your changes don't break existing functionality. These tests will run with
Github Actions when a pull request is made. More details on running the tests locally can be found
[here](https://github.com/newrelic/newrelic-python-agent/blob/main/CONTRIBUTING.rst#testing-guidelines),
For most contributions it is strongly recommended to add additional tests which
exercise your changes.

### CODE REVIEW

**Comment by lrafeei** [comment]
Hi @GabrielCappelli--sorry about the delay.  We are hoping to get to this either this week or next.

**Comment by Ak-x** [comment]
Hello @GabrielCappelli could you please sign the CLA.

**Comment by GabrielCappelli** [comment]
> Hello @GabrielCappelli could you please sign the CLA.

Hey, I believe I already have

image

**Comment by hmstepanek** [comment]
Hi, there are places where we don't want to propagate the current trace to the thread such as task queues where the task is itself a separate transaction so we will not accept this change as it makes assumptions that are not always correct. That being said, you are welcome to use this implementation as an extension to the agent in cases where you do want this behavior.

**Pull request closed without merging**
