### PR TITLE
Added separate instrumentation for redis.asyncio.client

### PR DESCRIPTION
**Pull request by ahmedhr**
# Overview
This PR will add a new instrumentation for redis.asyncio.client and remove aioredis' intrumentation dependency

## This PR creates a separate instrumentation for `redis.asyncio.client` initially, instrumentation of aioredis was used which is a different package to add async support to redis. Since async support is now directly added in `redis`  as `redis.asyncio` we can directly use a new instrumentation.

# Related Github Issue
Closes the issue https://github.com/newrelic/newrelic-python-agent/issues/807

### CODE REVIEW

**Comment by ahmedhr** [comment]
@hmstepanek @umaannamalai can you verify and let me know the next steps for merging this PR?

**Comment by ahmedhr** [comment]
@lrafeei can help with this PR? 
how should we proceed with this?

**Comment by lrafeei** [comment]
> @lrafeei can help with this PR? how should we proceed with this?

Hi @ahmedhr--sorry about the delay on this.  I'll look at this now and work on merging this in.  Thanks for the contribution!

**Comment by lrafeei** [comment]
Overall, looks great!  I'll just add a few changes for testing/supportability window purposes and we can merge this in.

**Comment by ahmedhr** [comment]
Hi @lrafeei,

The issue has been introduced again, since we have added aioredis instrumentation( `instrument_aioredis_client` ) for `redis.asyncio.client` and `redis.asyncio.commands`.

We should remove aioredis intrumentation for redis.asyncio , since aioredis instrumentation is already there for `aioredis.client` and `aioredis.commands`.


We do not need `instrument_aioredis_client` for any version of `redis.asyncio`.

also, I'm adding a new commit to remove `redis.asyncio`'s dependency from `aioredis`.

Please check the new changes.
Thanks

**Comment by lrafeei** [comment]
> Hi @lrafeei,
> 
> The issue has been introduced again, since we have added aioredis instrumentation( `instrument_aioredis_client` ) for `redis.asyncio.client` and `redis.asyncio.commands`.
> 
> We should remove aioredis intrumentation for redis.asyncio , since aioredis instrumentation is already there for `aioredis.client` and `aioredis.commands`.
> 
> We do not need `instrument_aioredis_client` for any version of `redis.asyncio`.
> 
> also, I'm adding a new commit to remove `redis.asyncio`'s dependency from `aioredis`.
> 
> Please check the new changes. Thanks

Hi @ahmedhr,

The reason I included the older references to the instrumentation is that New Relic has a 2 year support window for instrumented frameworks, so the aioredis and aredis instrumentation has to stay for that amount of time, even though redis now supports asyncio (The good news here is that the version of redis that supports Python 2.7 is outside of our support window, so that makes testing easier). Once we make sure that's accounted for as well as adding test(s) for the newly added instrumentation, we can finally merge this in.

**Comment by ahmedhr** [comment]
> > Hi @lrafeei,
> > 
> > The issue has been introduced again, since we have added aioredis instrumentation( `instrument_aioredis_client` ) for `redis.asyncio.client` and `redis.asyncio.commands`.
> > 
> > We should remove aioredis intrumentation for redis.asyncio , since aioredis instrumentation is already there for `aioredis.client` and `aioredis.commands`.
> > 
> > We do not need `instrument_aioredis_client` for any version of `redis.asyncio`.
> > 
> > also, I'm adding a new commit to remove `redis.asyncio`'s dependency from `aioredis`.
> > 
> > Please check the new changes. Thanks
> 
> Hi @ahmedhr,
> 
> The reason I included the older references to the instrumentation is that New Relic has a 2 year support window for instrumented frameworks, so the aioredis and aredis instrumentation has to stay for that amount of time, even though redis now supports asyncio (The good news here is that the version of redis that supports Python 2.7 is outside of our support window, so that makes testing easier). Once we make sure that's accounted for as well as adding test(s) for the newly added instrumentation, we can finally merge this in.

Hi @lrafeei,


Since aioredis instrumentation is already there, and I have just replaced aredis with the new instrumentation, this will work for all the redis versions. Because for older redis versions there was no async support. 

Adding older references doesn't check the redis version when applying the instrumentation, it applies both the instruments when aredis is used.

If you check, the current get package function in aioredis hampers the performance by a very big margin.

**Comment by TimPansino** [comment]
> If you check, the current get package function in aioredis hampers the performance by a very big margin.

That's a separate issue, one that there's a PR open for.

Based on codecov this code is entirely untested as of now, we're going to need to add tests before we can release this.

@lrafeei let's redirect to a development branch and group this together with the other redis open source contributions. Add testing for everything in a new PR, and merge it all back to main at once with no squashing to preserve this history.

**Comment by ahmedhr** [comment]
Thanks @TimPansino, @lrafeei.
I am currently using this in my project, will report if I find any bugs.

Anything else I can help with?

**Comment by lrafeei** [comment]
@ahmedhr If you could add tests for the new code, that could help.  Otherwise, I'll work on adding those myself in the coming week in a separate PR

**Review by lrafeei — APPROVED** [review]

**Pull request merged**
