### PR TITLE
replace deprecated inspect.formatargspec with successor inspect.signa…

### PR DESCRIPTION
**Pull request by dylan-grafmyre**
…ture

# Overview
replace calls to deprecated function calls, currently emitting warnings, with successor function calls which do not emit warnings

# Related Github Issue
no issue

# Testing
no behavior was intended to be changed, existing tests may cover this case

### CODE REVIEW

**Comment by mwgamble** [comment]
Would love to see this get merged in the near future. The deprecation warnings are getting very annoying.

**Comment by coreyarnold** [comment]
@dylan-grafmyre Can you go ahead and sign the Contributors License Agreement (https://cla-assistant.io/newrelic/newrelic-python-agent?pullRequest=99) using the github account you made the PR with when you have a moment?

Happy coding,
Corey

**Comment by umaannamalai** [comment]
Hi @dylan-grafmyre - we would like to accept this fix with a couple of tweaks on our end! It would be great if you could sign the Contributors License Agreement at your earliest convenience so that we can get this PR merged.
Thank you for contributing!

**Comment by mwgamble** [comment]
I'm not super familiar with how all of these things work, and I'm not the author of the PR, but personally I'd be a bit frustrated if the first response after five months was "please sign the CLA".

This is clearly an issue that affects everyone and is going to be a blocker for upgrading python in the near future if it isn't fixed. The only reason a member of the community felt the need to submit this PR is because New Relic haven't fixed it themselves.

If New Relic know this deprecation warning is a problem, and you already intend to make some additional changes, why don't you just fix it yourselves internally?

Let's hypothesise for a moment. What happens if the original author doesn't get back in a reasonable amount of time to sign the CLA? Will New Relic be forever unable to merge a fix for the deprecation warning because someone not employed by New Relic first authored a fix? Presumably not, because it would be incredibly inconvenient for your customers. So why not just fix it internally to save the time of those in the community?

**Pull request closed without merging**
