### PR TITLE
Defensively check GQL path parts in framework_graphql

### PR DESCRIPTION
**Pull request by jollysahil**
# Overview
When constructing deepest path, removes None values from path parts and fields

# Related Github Issue
#814 

# Testing
The agent includes a suite of tests which should be used to
verify your changes don't break existing functionality. These tests will run with
Github Actions when a pull request is made. More details on running the tests locally can be found
[here](https://github.com/newrelic/newrelic-python-agent/blob/main/CONTRIBUTING.rst#testing-guidelines),
For most contributions it is strongly recommended to add additional tests which
exercise your changes.

### CODE REVIEW

**Review by hmstepanek — CHANGES_REQUESTED** [review]
Thanks for implementing a fix for this! Could you also create a [test](https://github.com/newrelic/newrelic-python-agent/blob/main/tests/framework_graphql/test_application.py) that reproduces the error in https://github.com/newrelic/newrelic-python-agent/issues/814?

**Comment by jollysahil** [comment]
@hmstepanek thanks for your review, I have pushed up a query which I believe causes the error. I haven't been able to get the test to run locally - do you have any documentation on the steps needed to install dependencies/run tests?

**Comment by jollysahil** [comment]
@hmstepanek just checking back on this?

**Comment by jollysahil** [comment]
closing due to lack of follow up

**Pull request closed without merging**
