### PR TITLE
Created a log handler that forwards logs to new relic api

### PR DESCRIPTION
**Pull request by iamr0b0tx**
_Before contributing, please read our [contributing guidelines](https://github.com/newrelic/newrelic-python-agent/blob/main/CONTRIBUTING.rst) and [code of conduct](https://github.com/newrelic/.github/blob/master/CODE_OF_CONDUCT.md)._

# Overview
I created a handler `NewRelicLogHandler` that can be used in python applications like Django as a log handler. The handler forwards logs to the API.

# Related Github Issue
related to issue #439 

# Testing
Please advise on this. I am not sure what and how to test given is suppose to make and API call

### CODE REVIEW

**Comment by TimPansino** [comment]
Hello @iamr0b0tx, thank you for your contribution!

We've got big changes coming for logging in the next quarter, but in the meantime I like this solution. We'll go ahead and merge this and make all the changes we need to on a separate PR to get this up to our standards. You can expect this to release with a similar API in the next release of the agent. 

In the future it may be replaced during our larger logging efforts, but I think we'll try to keep a simple solution like this available.

**Comment by iamr0b0tx** [comment]
@TimPansino I am looking forward to it. Thanks

**Review by TimPansino — APPROVED** [review]

**Comment by TimPansino** [comment]
@iamr0b0tx can you update this branch with main so I can merge this?

**Comment by iamr0b0tx** [comment]
@TimPansino Done!

**Pull request merged**
